# Use a imagem do Node.js
FROM node:14

# Defina o diretório de trabalho no contêiner
WORKDIR /app

# Copie o package.json e package-lock.json para o diretório de trabalho
COPY package*.json ./

# Instale as dependências
RUN npm install

# Copie o código do projeto para o diretório de trabalho
COPY . .

# Exponha a porta na qual o servidor estará rodando
EXPOSE 3001

# Comando para rodar o servidor
CMD ["node", "server.js"]
